version="1.0.0" # this defines what your config file version is; it should not be touched
updateFrequency=3600 # 3600ms is 60 minutes
additionalIpProviders=[""] # note that the server must return a JSON object where "ip" is the property with the IP address
copyIPv6=false # this will be implemented another day
target="vercel" # choose between vercel or cloudflare as nameserver
past="" # DO NOT TOUCH THIS PROPERTY, IT IS FOR TRACKING FILE CHANGES

[vercel]
authToken="token_goes_here" # this can also be stored as an environment variable (VERCEL_AUTH_TOKEN)
dnsReturnInstanceLimit=20
domainTarget=["example.com"] # do not include protocols such as http:// or https://

[cloudflare]
authToken="token_goes_here" # this can also be stored as an environment variable (CLOUDFLARE_AUTH_TOKEN)
domainTarget=["example.com"]

[[record]]
recordType="A"
comment="For our Minecraft server"
ttl=60
name="mc"

[[record]]
recordType="A"
comment="Web server"
ttl=80
name="*"